language: node_js
notifications:
  email: false
node_js:
  - '6'
cache:
  yarn: true
before_install:
  - npm i -g codecov
script:
  - yarn run lint
  - yarn run cover-client
  - codecov
  - yarn run build

# If sudo is disabled, CI runs on container based infrastructure (allows caching &c.)
sudo: false

# Notify us of the build status on the Slack channel
notifications:
  slack: conveyal:WQxmWiu8PdmujwLw4ziW72Gc

# Push results to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn run semantic-release
