site_name: Transit Data Tools Docs
site_url: http://mtc-datatools.readthedocs.io
repo_url: https://github.com/conveyal/datatools-manager
theme: readthedocs
extra_css: [style.css]

pages:
- Home: 'index.md'
- User Guide:
    - 'Introduction': 'user/introduction.md'
    - 'Managing Projects & Feeds': 'user/managing-projects-feeds.md'
    - 'Managing Users': 'user/managing-users.md'
    - 'Service Alerts Manager': 'user/service-alerts.md'
    - 'eTID Configuration Manager': 'user/sign-config.md'
    - 'Searching for Routes and Stops': 'user/searching-routes-stops.md'
    - 'GTFS+ Editor': 'user/gtfs-plus-editor.md'
    - 'Appendix: GTFS Validation Warnings': 'user/appendix-gtfs-warnings.md'
- Development Guide:
    - 'Deployment': 'dev/deployment.md'
    - 'Development': 'dev/development.md'
