entries:
  - lib/main.js:dist/index.js
  - lib/index.css:dist/index.css
application:
  data:
    gtfs_s3_bucket: bucket-name
    use_s3_storage: false
  title: Transit Café
  logo: http://gtfs-assets-dev.conveyal.com/data_manager.png # defaults to src/main/client/assets/application_logo.png
  active_project: project-id
  notifications_enabled: false
  docs_url: https://5tsrl.github.io/datatools-ui/
  changelog_url: https://changelog.example.com
  support_email: cafe@5t.torino.it
  #date_format: MMM Do YYYY
  date_format: DD.MM.YYYY
modules:
  enterprise:
    enabled: false
  editor:
    enabled: true
  user_admin:
    enabled: true
  validator:
    enabled: true
extensions:
  transitland:
    enabled: false
  transitfeeds:
    enabled: false
