site_name: Conveyal Transit Data Tools
site_url: http://mtc-datatools.readthedocs.io
repo_url: https://github.com/conveyal/datatools-manager
docs_dir: ../docs
site_dir: ../target/mkdocs
theme: readthedocs

pages:
- Home: 'index.md'
- User Guide:
    - 'Introduction': 'user/introduction.md'
    - 'Managing Projects & Feeds': 'user/managing-projects-feeds.md'
    - 'Managing Users': 'user/managing-users.md'
    - 'Service Alerts Manager': 'user/service-alerts.md'
    - 'eTID Configuration Manager': 'user/sign-config.md'
    - 'Appendix: GTFS Validation Warnings': 'user/appendix-gtfs-warnings.md'
- Development Guide:
    - 'Deployment': 'dev/deployment.md'
    - 'Development': 'dev/development.md'
